services:
  disease-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    environment:
      - SERVER_PORT=3030
      - UMLS_URL=${UMLS_URL}
      - UMLS_KEY=${UMLS_KEY}
      - ICD_URL=${ICD_URL}
      - ICD_TOKEN_URL=${ICD_TOKEN_URL}
      - ICD_CLIENT_ID=${ICD_CLIENT_ID}
      - ICD_CLIENT_SECRET=${ICD_CLIENT_SECRET}
      - DB_URL=my-sql:3306
      - DB_NAME=umls
      - DB_USER=test
      - DB_PASSWORD=test
      - CACHE_URL=${CACHE_URL}
      - CACHE_PASSWORD=${CACHE_PASSWORD}
      - CACHE_TTL_SEC=${CACHE_TTL_SEC:-86400} # 1 day
      - DEBUG=${DEBUG}
    depends_on:
      - cache
      - my-sql
    restart: unless-stopped

  ollama:
    image: ollama/ollama:0.12.0
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./pull-medical-llm.sh:/entrypoint.sh
    restart: unless-stopped
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]

  cache:
    image: redis:8.0.1
    command: redis-server --requirepass ${CACHE_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - cache_data:/data
    environment:
      - REDIS_PASSWORD=${CACHE_PASSWORD}
    restart: unless-stopped

  my-sql:
    image: mysql:9.4.0
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=umls
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./go-api/db/UMLS/DATA:/umls_data
      - ./go-api/db/UMLS/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh:ro
      - ./go-api/db/UMLS/healthcheck.sh:/healthcheck.sh:ro
    command:
      - --secure-file-priv=umls_data
    restart: unless-stopped

volumes:
  cache_data:
  ollama_data:
  mysql_data:
